name: footy
favicon: null
layout_spectrum: 0.7274666866287589
typography_spectrum: 0.3825383859220892
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.35742876632139087
  lightness: 0.4216509433463216
  saturation: 0.37784894090145826
  rhythmicContrast: 0.5375715396367013
purpose: []
